services:
  hello:
    image: ricardo03/hello-img:${IMAGE_TAG} 
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      ENVIRONMENT_NAME: local
      MONGODB_CONECTION_URL: mongodb://root:example@host.docker.internal:27017/   # Changed
    restart: always
    profiles:
      - "hello-service"

  jenkins:
    image: jenkins/jenkins
    ports:
      - 8082:8080
      - 50000:50000
    restart: on-failure
    volumes:
      - /workspaces/jenkins_config:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./Dockerfile:/Dockerfile
      - /usr/libexec/docker/cli-plugins/docker-compose:/usr/libexec/docker/cli-plugins/docker-compose
    environment:
      MONGODB_CONECTION_URL: mongodb://root:example@host.docker.internal:27017/   # Changed
    profiles:
      - "hello-service"
    user: 0:0
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    image: mongo:6.0.20
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    profiles:
      - "mongo"

  mongo-admin-ui:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@host.docker.internal:27017/   # Changed
      ME_CONFIG_BASICAUTH_USERNAME: unibuc
      ME_CONFIG_BASICAUTH_PASSWORD: adobe
    profiles:
      - "mongo"
