global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'email'
  
receivers:
- name: 'email'
  email_configs:
  - to: 'denis.denis67889@gmail.com'
    from: 'test.test@gmail.com'
    smarthost: app.debugmail.io:25 
    auth_username: 'dc3360ba-3356-4de5-9bbb-ef82f59d488e'
    auth_identity: 'dc3360ba-3356-4de5-9bbb-ef82f59d488e'
    auth_password: '446b4fe3-b10a-4ae3-a640-9e4559951978'
